{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-role-binding
  namespace: {{.Values.namespace }}
  labels:
    {{- include "jupyter-spark.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{.Values.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
