apiVersion: v1
kind: Service
metadata:
  name: {{ include "jupyter-spark.fullname" . }}
  labels:
    {{- include "jupyter-spark.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portui }}
      targetPort: {{ .Values.service.portui }}
      protocol: TCP
      name: ui
    - port: {{ .Values.service.portsparkui }}
      targetPort: {{ .Values.service.portsparkui }}
      protocol: TCP
      name: sparkui
    - port: {{ .Values.service.portdriver }}
      targetPort: {{ .Values.service.portdriver }}
      protocol: TCP
      name: driver
    - port: {{ .Values.service.portblockmanager }}
      targetPort: {{ .Values.service.portblockmanager }}
      protocol: TCP
      name: blockmanager
  selector:
    {{- include "jupyter-spark.selectorLabels" . | nindent 4 }}
